# Generated by Django 4.0.4 on 2022-05-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_images_image_images_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='photo_image',
        ),
    ]
