# Generated by Django 4.0.4 on 2022-05-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_image_images_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='photo_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
    ]
