# Generated by Django 4.0.4 on 2022-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_photo_image_images_image_remove_images_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='brian', upload_to='images/'),
        ),
    ]
