# Generated by Django 4.0.4 on 2022-05-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_images_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name']},
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='images_image',
        ),
    ]
